package com.example.data.repository

import com.example.data.local.*
import com.example.data.model.*
import kotlinx.coroutines.flow.Flow

class AcademicRepository(
    private val courseDao: CourseDao,
    private val timetableDao: TimetableDao,
    private val makeupDao: MakeupDao,
    private val notificationDao: NotificationDao,
    private val outboxDao: OutboxDao,
    private val userDao: UserDao
) {
    val allCourses: Flow<List<Course>> = courseDao.getAllCourses()
    val allSessions: Flow<List<ClassSession>> = timetableDao.getAllSessions()
    val allMakeupOpportunities: Flow<List<MakeupOpportunity>> = makeupDao.getAllMakeupOpportunities()
    val pendingOpportunities: Flow<List<MakeupOpportunity>> = makeupDao.getPendingOpportunities()
    val allNotifications: Flow<List<AcademicNotification>> = notificationDao.getAllNotifications()
    val unreadNotificationsCount: Flow<Int> = notificationDao.getUnreadCount()
    val outboxEvents: Flow<List<OutboxEvent>> = outboxDao.getAllEvents()
    val allUsers: Flow<List<UserAccount>> = userDao.getAllUsersFlow()

    fun getUsersByRole(role: UserRole): Flow<List<UserAccount>> = userDao.getUsersByRoleFlow(role)

    suspend fun authenticateUser(idOrEmail: String, pass: String): UserAccount? =
        userDao.authenticate(idOrEmail.trim(), pass)

    suspend fun authenticateUserWithRole(idOrEmail: String, pass: String, role: UserRole): UserAccount? =
        userDao.authenticateWithRole(idOrEmail.trim(), pass, role)

    suspend fun registerUser(user: UserAccount) = userDao.insertUser(user)
    suspend fun getUserById(userId: String): UserAccount? = userDao.getUserById(userId)
    suspend fun deleteUser(userId: String) = userDao.deleteUserById(userId)
    suspend fun updateUser(user: UserAccount) = userDao.updateUser(user)

    fun getSessionsForDay(dayOfWeek: Int): Flow<List<ClassSession>> =
        timetableDao.getSessionsForDay(dayOfWeek)

    suspend fun cancelClassSession(session: ClassSession, reason: String) {
        // 1. Update session status
        timetableDao.updateSessionStatus(session.id, SessionStatus.CANCELLED, reason)

        // 2. Insert outbox event for transactional offline-first pipeline
        val event = OutboxEvent(
            eventType = "CLASS_CANCELLED",
            payloadJson = "{\"sessionId\": ${session.id}, \"courseCode\": \"${session.courseCode}\", \"reason\": \"$reason\"}",
            status = "PENDING"
        )
        outboxDao.insertEvent(event)

        // 3. Create self-healing recovery opportunity
        val makeup = MakeupOpportunity(
            cancelledSessionId = session.id,
            courseCode = session.courseCode,
            courseName = session.courseName,
            instructorName = session.instructorName,
            targetDayOfWeek = if (session.dayOfWeek == 1) 4 else 5,
            targetDayName = if (session.dayOfWeek == 1) "Thursday" else "Friday",
            targetTimeSlot = "11:30 - 12:20 (Period 4)",
            targetPeriodIndex = 4,
            targetDurationSlots = session.durationSlots,
            targetRoom = session.roomName,
            compatibilityScore = 95,
            teacherAvailable = true,
            studentsAvailable = true,
            roomSuitable = true,
            conflictReason = "Generated by Cross-Cancellation Engine. No hard violations.",
            isAccepted = false,
            isRejected = false,
            votesCount = 38,
            totalStudents = 48
        )
        makeupDao.insertOpportunity(makeup)

        // 4. Create Notification
        val notification = AcademicNotification(
            title = "Class Disruption: ${session.courseCode}",
            message = "${session.courseCode} ${session.sessionType.label} marked cancelled. Self-healing optimizer initiated recovery search.",
            category = NotificationCategory.CANCELLATION,
            relatedEntityId = session.id,
            actionText = "View Recovery"
        )
        notificationDao.insertNotification(notification)
    }

    suspend fun acceptMakeupOpportunity(opportunity: MakeupOpportunity) {
        makeupDao.acceptOpportunity(opportunity.id)

        // Create new rescheduled class session
        val rescheduledSession = ClassSession(
            courseId = opportunity.id,
            courseCode = opportunity.courseCode,
            courseName = opportunity.courseName,
            instructorName = opportunity.instructorName,
            roomName = opportunity.targetRoom,
            dayOfWeek = opportunity.targetDayOfWeek,
            periodIndex = opportunity.targetPeriodIndex,
            durationSlots = opportunity.targetDurationSlots,
            timeDisplay = opportunity.targetTimeSlot,
            sessionType = SessionType.MAKEUP,
            status = SessionStatus.PUBLISHED,
            originalSessionId = opportunity.cancelledSessionId,
            notes = "Self-healing recovery session scheduled after coordinator and student alignment."
        )
        timetableDao.insertSession(rescheduledSession)

        // Record outbox event
        outboxDao.insertEvent(
            OutboxEvent(
                eventType = "MAKEUP_ACCEPTED",
                payloadJson = "{\"opportunityId\": ${opportunity.id}, \"courseCode\": \"${opportunity.courseCode}\"}",
                status = "PENDING"
            )
        )

        // Notification
        notificationDao.insertNotification(
            AcademicNotification(
                title = "Makeup Class Confirmed! ✨",
                message = "${opportunity.courseCode} makeup session confirmed for ${opportunity.targetDayName} at ${opportunity.targetTimeSlot} in ${opportunity.targetRoom}.",
                category = NotificationCategory.MAKEUP_FOUND,
                relatedEntityId = opportunity.id
            )
        )
    }

    suspend fun rejectMakeupOpportunity(opportunity: MakeupOpportunity) {
        makeupDao.rejectOpportunity(opportunity.id)
    }

    suspend fun voteForOpportunity(id: Long) {
        makeupDao.voteForOpportunity(id)
    }

    suspend fun markNotificationRead(id: Long) {
        notificationDao.markAsRead(id)
    }

    suspend fun markAllNotificationsRead() {
        notificationDao.markAllAsRead()
    }

    suspend fun replaceRoutineSessions(newSessions: List<ClassSession>, semester: Int? = null) {
        if (semester != null) {
            timetableDao.deleteSessionsForSemester(semester)
        } else {
            timetableDao.deleteAllSessions()
        }
        timetableDao.insertSessions(newSessions)
    }

    suspend fun insertCustomCourses(courses: List<Course>) {
        courseDao.insertCourses(courses)
    }
}
